[phases.setup]
nixPkgs = ['nodejs_20', 'python311']

[phases.install]
cmds = [
  'npm ci --include=dev',
  'pip install --no-cache-dir flask flask-cors psycopg2-binary pydantic python-dotenv requests'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'
