[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production.variables]
NODE_ENV = "production"
USE_NODE_BACKEND = "true"

[environments.python.variables]
NODE_ENV = "production"
USE_NODE_BACKEND = "false"